service: lambda-dynamicform

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

custom:
  webpack:
    includeModules:
      packagePath: "../package.json" # relative path to custom package.json file.
